### ISSUE TITLE
USER STORY: View Page

### ISSUE THREAD

**Issue by AndreeeasN** [AndreeeasN/pp5-project#1]
USER STORY:
As a **Site Visitor** I can **visit the page** so that **I can view it's contents**

**Acceptance criteria**
1. Allow users to view the main page

**Tasks**
- [ ] create base html template
- [ ] create index html template 
- [ ] connect template via urls.py

Story points: 5
