### ISSUE TITLE
USER STORY: Site Alerts

### ISSUE THREAD

**Issue by AndreeeasN** [AndreeeasN/pp5-project#10]
USER STORY:
As a **Site Visitor** I can **receive alert messages** so that **I can get confirmations that my actions went through successfully**

**Acceptance criteria**
1. user receives a notifications upon committing account actions or purchases
2. the notification can be closed manually and disappears automatically after a short time

**Tasks**
- [x] create message box in base.html containing all {{ message.tags }}
- [ ] make a javascript function that automatically closes the message box
- [ ] add confirmation/alert messages to purchase-related events through views.py

Story Points: 2
