### ISSUE TITLE
USER STORY: Select Sizes

### ISSUE THREAD

**Issue by AndreeeasN** [AndreeeasN/pp5-project#12]
USER STORY:
As a **Site Visitor** I can **select varying bag sizes** so that **I can order the amount I want**

**Acceptance criteria**
1. user can choose from a pre-made list of sizes for certain products
2. the price is updated when selecting a different size
3. when displaying prices for the product, it starts from the lowest price

**Tasks**
- [ ] create a model for variants of products
- [ ] add variant-specific behaviours to products template
- [ ] create js script to update price when new size is selected

Story Points: 3
