### ISSUE TITLE
USER STORY: Add to cart

### ISSUE THREAD

**Issue by AndreeeasN** [AndreeeasN/pp5-project#14]
USER STORY:
As a **Site Visitor** I can **add products to the cart** so that **I can purchase several products at once**

**Acceptance criteria**
1. Products can be added through the products page
2. Added products can be viewed through the cart page
3. The cart page displays quantity, prices and grand total

**Tasks**
- [x] create new cart app
- [x] create a template to view all cart items
- [x] create a view that allows adding/removing products from session cart
- [x] connect template through urls.py
- [x] add cart contents to site context to allow further interactions

Story Points: 5
