### ISSUE TITLE
USER STORY: Checkout

### ISSUE THREAD

**Issue by AndreeeasN** [AndreeeasN/pp5-project#15]
USER STORY:
As a **Site Visitor** I can **checkout the contents of my cart** so that **I can pay and receive my products**

**Acceptance criteria**
1. User can reach checkout directly from their cart
2. User can enter billing information and finalize their purchase
3. User is shown an order confirmation (also sent to their email)
4. User cart is emptied upon purchase

**Tasks**
- [ ] create new checkout app
- [ ] install Stripe
- [ ] create view that handles payment through Stripe
- [ ] build checkout and checkout_success template
- [ ] connect templates through urls.py

Story Points: 8
