### ISSUE TITLE
USER STORY: Save Billing Information

### ISSUE THREAD

**Issue by AndreeeasN** [AndreeeasN/pp5-project#17]
USER STORY:
As a **Regular Customer** I can **save my billing information** so that **I can quickly and easily make repeat orders**

**Acceptance criteria**
1. User can enter their billing information into their profile page
2. User has option to save their information on checkout

**Tasks**
- [x] create form containing all required user information
- [x] add form to user profile
- [x] create view that saves form info to user profile
- [x] alter checkout view to include user information if available

Story Points: 3
