### ISSUE TITLE
USER STORY: Remove/Adjust Cart Items

### ISSUE THREAD

**Issue by AndreeeasN** [AndreeeasN/pp5-project#18]
USER STORY:
As a **Site Visitor** I can **remove or change quantity of cart items** so that **I can undo any potential misclicks**

**Acceptance criteria**
1. User can remove items from their cart
2. User can alter the quantity of an item in their cart

**Tasks**
- [x] alter checkout view to include removal of cart items by id
- [x] adjust checkout template to contain a remove button and quantity adjusting buttons
- [x] limit quantity adjuster buttons to only accept numerics between 1-99 using js

Story Points: 2
