### ISSUE TITLE
USER STORY: Add new Products

### ISSUE THREAD

**Issue by AndreeeasN** [AndreeeasN/pp5-project#19]
USER STORY:
As a **Site Admin** I can **add new products** so that **the store can start selling new things**

**Acceptance criteria**
1. Superusers can reach an "add new product" form from the menu
2. All information required to create a new product is available from the form
3. Only superusers have access to this function

**Tasks**
- [x] create 'add new product' template
- [x] create form containing all fields required to create a new product
- [x] create view that creates product and adds to database

Story Points: 3
