### ISSUE TITLE
USER STORY: Sign Up

### ISSUE THREAD

**Issue by AndreeeasN** [AndreeeasN/pp5-project#2]
USER STORY:
As a **Site Visitor** I can **sign up** so that **I have a personal account to interact with the website through**

**Acceptance criteria**
1. users can sign up for an account
2. users have access to the sign-up page from the navbar / log-in page

**Tasks**
- [ ] install allauth
- [ ] create page for sign-up
- [ ] add allauth form to sign-up page
- [ ] connect page via urls.py
- [ ] add link to login from base.html and the log-in page

Story points: 3
