### ISSUE TITLE
USER STORY: Edit Products

### ISSUE THREAD

**Issue by AndreeeasN** [AndreeeasN/pp5-project#20]
USER STORY:
As a **Site Admin** I can **edit products** so that **the store can adjust product details**

**Acceptance criteria**
1. Superusers can reach an "edit product" form from the products / product details page
2. Form is pre-filled with already existing product details
3. Only superusers have access to this function

**Tasks**
- [x] create 'edit product' template
- [x] create form containing required product details
- [x] create view that updates product

Story Points: 3
