### ISSUE TITLE
USER STORY: Sort by Tags

### ISSUE THREAD

**Issue by AndreeeasN** [AndreeeasN/pp5-project#22]
USER STORY:
As a **Site Visitor** I can **include/exclude certain tags during my search** so that **I can easily find products I'm looking for**

**Acceptance criteria**
1. Products page has a dropdown menu featuring all tags from products in current search
2. User can de-select certain tags to products using that tag

**Tasks**
- [ ] add new dropdown menu to products page
- [ ] create new view that displays all tags on current products in dropdown menu
- [ ] alter products view to include/exclude tags in search results

Story Points: 3
