### ISSUE TITLE
USER STORY: Log in

### ISSUE THREAD

**Issue by AndreeeasN** [AndreeeasN/pp5-project#3]
USER STORY:
As a **Site Visitor** I can **log in** so that **I can interact with the website**

**Acceptance criteria**
1. users can log in
2. users have access to the page from the navbar

**Tasks**
- [ ] create page for sign-in
- [ ] add allauth form to sign-in page
- [ ] connect page via urls.py
- [ ] add link to login from base.html

Story points: 2
