### ISSUE TITLE
USER STORY: Log Out

### ISSUE THREAD

**Issue by AndreeeasN** [AndreeeasN/pp5-project#4]
USER STORY:
As a **Site Visitor** I can **log out of my account** so that **I can avoid someone else accessing my account**

**Acceptance criteria**
1. users can log out
2. users have access to the logout button from the navbar

**Tasks**
- [ ] create confirmation page for signing out
- [ ] connect page via urls.py
- [ ] add link to navbar in base.html

Story points: 2
