### ISSUE TITLE
USER STORY: Password Recovery

### ISSUE THREAD

**Issue by AndreeeasN** [AndreeeasN/pp5-project#5]
USER STORY:
As a **Site Visitor** I can **recover my password** so that **I can keep using my account if I lose the password**

**Acceptance criteria**
1. users can click 'recover password' from the sign-in page
2. users are sent an e-mail containing a password recovery link

**Tasks**
- [x] set up new e-mail adress for the project
- [x] set e-mail backend settings in settings.py
- [x] add e-mail credentials to heroku
- [x] add 'forgot password' link to sign-in page
- [x] create simple password recovery page
- [x] connect both urls via urls.py

Story points: 5
