### ISSUE TITLE
USER STORY: View Products

### ISSUE THREAD

**Issue by AndreeeasN** [AndreeeasN/pp5-project#6]
USER STORY:
As a **Site Visitor** I can **view a list of products** so that **see what's available for purchase**

**Acceptance criteria**
1. user can view a list of available products
2. the product list displays name/price/content

**Tasks**
- [ ] create a product model containing all required information
- [ ] create a view that returns a queryset of all products
- [ ] build a page template that displays the products
- [ ] connect the page via urls.py

Story points: 5
