### ISSUE TITLE
USER STORY: Searching

### ISSUE THREAD

**Issue by AndreeeasN** [AndreeeasN/pp5-project#7]
USER STORY:
As a **Site Visitor** I can **search for products** so that **I can find what I'm looking for**

**Acceptance criteria**
1. a search bar is available from the navbar
2. user search includes product name, description and contents
3. search results are displayed on the search page in order

**Tasks**
- [ ] create a search filter in filters.py
- [ ] create a function in views that filters posts using the search filter
- [ ] display search results on template page

Story points: 3
