### ISSUE TITLE
USER STORY: View Product Details

### ISSUE THREAD

**Issue by AndreeeasN** [AndreeeasN/pp5-project#9]
USER STORY:
As a **Site Visitor** I can **view product details** so that **I can see more information about my potential purchase**

**Acceptance criteria**
1. user can view product details by clicking on a product
2. the product details includes at minimum name, description, price and 'add to cart' button

**Tasks**
- [ ] build a page template that displays the specified product
- [ ] create a view that includes required product information as context
- [ ] connect the page via urls.py

Story points: 3
